name: tracer
version: 0.1.0.0
git: git@gitlab.com:G3ntleMan/path.git
license: MIT
author:
  - Gijs van Steenpaal
  - Robbert van der Helm
copyright: 2019 Gijs van Steenpaal, Robert van der Helm

extra-source-files:
  - app/assets/**/*
  - README.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the included README file.

dependencies:
  - base >= 4.7 && < 5
  - accelerate
  - accelerate-io-vector
  - bytestring
  - deepseq
  - lens
  - lens-accelerate
  - linear
  - linear-accelerate
  - mwc-random
  - template-haskell
  - transformers
  - text
  - vector

  # OpenGL related packages
  - GLUtil
  - OpenGL
  - sdl2
  - sdl2-ttf

# We don't need to compile the Accelerate backend we're not using. If we don't
# do this, you won't be able to compile the CPU version without having CUDA
# installed.
when:
  - condition: flag(cpu)
    then:
      dependencies: [accelerate-llvm-native]
    else:
      dependencies: [accelerate-llvm-ptx]

ghc-options:
  - -Wall

flags:
  cpu:
    description: "Run the application using Accelerate's CPU backend."
    manual: true
    default: false

library:
  source-dirs: src

  when:
    - condition: flag(cpu)
      cpp-options: -DUSE_CPU_BACKEND

executables:
  tracer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - tracer

tests:
  tracer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tracer
